name: Test Coverage

on: [push]
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Run tests and generate coverage report
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Generate coverage badge
        uses: vladopajic/go-test-coverage/action/source@a93b868a4cbcbf18dc3781650fad241f0020e609 # v2.18.8
        with:
          config: ./.testcoverage.yml
          git-branch: badges
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
