# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go 1.22.x
      uses: actions/setup-go@v5
      with:
        # Semantic version range syntax or exact version of Go
        go-version: '1.22.x'

    - name: Build
      run: go build -v ./...
